SELECT *
  FROM
       APP.ANAGRAFICA JOIN APP.BISOGNI JOIN APP.ANAG_BISOGNI ON APP.BISOGNI.ID = APP.ANAG_BISOGNI.ID_BISOGNO ON APP.ANAGRAFICA.ID = APP.ANAG_BISOGNI.ID_ANAGRAFICA
  WHERE APP.ANAG_BISOGNI.ID_ANAGRAFICA = 1




